service: ${self:custom.env.serviceName, 'unknown'}-service

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: ${self:custom.env.memorySize}
  stage: ${env:ENV, 'unstaged'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:service}-${self:provider.stage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  logRetentionInDays: ${self:custom.env.lambdaLogsRotation}
  lambdaHashingVersion: ${self:custom.env.lambdaHashingVersion}
  apiGateway:
    usagePlan:
      quota:
        limit: 5000
        offset: 0
        period: DAY
  iam:
    role: ${self:custom.env.role}

  environment:
    REGION: ${self:provider.region}
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}
    OMS_SNS_TOPIC_ARN: ${self:custom.omsSnsTopicArn}
    OMS_RESERVE_ORDER_EVENTS_QUEUE_URL: ${self:custom.omsReserveOrderEventsQueueUrl}
    CT_UPDATE_ORDER_EVENTS_QUEUE_URL: ${self:custom.ctUpdateOrderEventsQueueUrl}

custom:
  profiles: ${file(./sls/profiles.yml)}
  deploymentBuckets: ${file(./sls/deployment-buckets.yml)}
  accountId: "#{AWS::AccountId}"
  namePrefix: ${self:service}-${self:provider.stage}-${self:provider.region}
  webpack:
    packager: "yarn"
    keepOutputDirectory: true
  omsSnsTopicArn: { "Ref": omsSnsTopic }
  omsReserveOrderEventsQueueUrl: !Ref omsReserveOrderEventsQueue
  ctUpdateOrderEventsQueueUrl: !Ref ctUpdateOrderEventsQueue
  env: ${file(./sls/env.yml)}

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!.git"
    - "!.gitignore"
    - "!.editorconfig"
    - "!.eslintignore"
    - "!.eslintrc.js"
    - "!sls/**"
    - "!README.md"
    - "!serverless.yml"
    - "!jest.config.js"
    - "!tsconfig.json"
    - "!webpack.config.json"

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-deployment-bucket
  - serverless-uuid

functions:
  - ${file(./sls/functions.yml)}

resources:
  - ${file(./sls/resources.yml)}
